/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nuwc.interestengine.gui;

import com.nuwc.parser.NMEAParser;
import com.nuwc.interestengine.map.Ship;
import com.nuwc.interestengine.map.TriMarker;
import com.nuwc.interestengine.simulation.Simulation;
import com.nuwc.interestengine.simulation.SimulationChangeListener;
import com.nuwc.interestengine.simulation.SimulationState;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Dan
 */
public class OptionsPanel extends javax.swing.JPanel
{
    private List<Ship> ships;
    private Simulation simulation;
    private List<TriMarker> markers;
    private MainFrame mainFrame;

    public OptionsPanel(List<Ship> ships, Simulation simulation, List<TriMarker> markers, MainFrame mainFrame)
    {
        this.ships = ships;
        this.simulation = simulation;
        this.markers = markers;
        this.mainFrame = mainFrame;

        initListeners();
        initComponents();
    }

    private void initListeners()
    {
        simulation.addSimulationChangeListener(new StateChangeListener());
    }

    private ImageIcon getPlayIcon()
    {
        String path = "/com/nuwc/interestengine/resources/gui/route-play.png";
        return new ImageIcon(getClass().getResource(path));
    }

    private ImageIcon getPauseIcon()
    {
        String path = "/com/nuwc/interestengine/resources/gui/route-pause.png";
        return new ImageIcon(getClass().getResource(path));
    }

    private ImageIcon getStopIcon()
    {
        String path = "/com/nuwc/interestengine/resources/gui/route-stop.png";
        return new ImageIcon(getClass().getResource(path));
    }

    public void interruptSimulation()
    {
        if (simulation.getState() != SimulationState.STOPPED)
        {
            simulation.stop();
        }

        updatePanel();
    }

    public synchronized void updatePanel()
    {
        SimulationState state = simulation.getState();
        if (ships.isEmpty())
        {
            playPauseButton.setIcon(getPlayIcon());
            playPauseButton.setText("Play");
            stopButton.setEnabled(false);
            playPauseButton.setEnabled(false);
        }
        else if (state == SimulationState.STOPPED)
        {
            playPauseButton.setIcon(getPlayIcon());
            playPauseButton.setText("Play");
            stopButton.setEnabled(false);
            playPauseButton.setEnabled(true);
        }
        else if (state == SimulationState.PAUSED)
        {
            playPauseButton.setIcon(getPlayIcon());
            playPauseButton.setText("Play");
            stopButton.setEnabled(true);
            playPauseButton.setEnabled(true);
        }
        else
        {
            playPauseButton.setIcon(getPauseIcon());
            playPauseButton.setText("Pause");
            stopButton.setEnabled(true);
            playPauseButton.setEnabled(true);
        }
    }

    private class StateChangeListener implements SimulationChangeListener
    {
        public StateChangeListener()
        {
        }

        @Override
        public void stateChanged()
        {
            updatePanel();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        playPauseButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        nameLabel.setText("Name:");

        nameTextField.setText("Default Ship");

        typeLabel.setText("Type:");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargo Vessel", "Tanker", "Passenger Vessel", "High Speed Craft", "Tugs and Special Craft", "Fishing", "Pleasure Craft" }));

        playPauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nuwc/interestengine/resources/gui/route-play.png"))); // NOI18N
        playPauseButton.setText("Play");
        playPauseButton.setEnabled(false);
        playPauseButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                playPauseButtonActionPerformed(evt);
            }
        });

        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nuwc/interestengine/resources/gui/route-stop.png"))); // NOI18N
        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stopButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Load Data");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(typeLabel))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeComboBox, 0, 200, Short.MAX_VALUE)
                            .addComponent(nameTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playPauseButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playPauseButton)
                    .addComponent(stopButton))
                .addGap(79, 79, 79)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playPauseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_playPauseButtonActionPerformed
    {//GEN-HEADEREND:event_playPauseButtonActionPerformed
        playPauseButton.setEnabled(false);
        SimulationState state = simulation.getState();
        if (state == SimulationState.STOPPED)
        {
            playPauseButton.setIcon(getPauseIcon());
            playPauseButton.setText("Pause");
            simulation.start();
        }
        else if (state == SimulationState.PAUSED)
        {
            playPauseButton.setIcon(getPauseIcon());
            playPauseButton.setText("Pause");
            simulation.unpause();
        }
        else
        {
            playPauseButton.setIcon(getPlayIcon());
            playPauseButton.setText("Play");
            simulation.pause();
        }
        stopButton.setEnabled(true);
        playPauseButton.setEnabled(true);
    }//GEN-LAST:event_playPauseButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stopButtonActionPerformed
    {//GEN-HEADEREND:event_stopButtonActionPerformed
        stopButton.setEnabled(false);
        SimulationState state = simulation.getState();
        if (state != SimulationState.STOPPED)
        {
            playPauseButton.setIcon(getPlayIcon());
            playPauseButton.setText("Play");
            simulation.stop();
        }
    }//GEN-LAST:event_stopButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(this);

        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            File file = fileChooser.getSelectedFile();
            String path = file.getAbsolutePath();
            NMEAParser parser = new NMEAParser(path, markers);
            parser.parse();
            mainFrame.updateMap();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton playPauseButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
